// Configuration template file
// For local development: Copy this file to config.js
// For production: The config.js is auto-generated by GitHub Actions

const CONFIG = {
    // n8n webhook URL - Your n8n workflow endpoint
    // All responses (answer, followup_question01, followup_question02) come from n8n
    n8nWebhookUrl: 'https://n8n.srv1155798.hstgr.cloud/webhook/8f0737aa-cde7-4089-bd96-7690120f89f7/chat',
    
    // Restaurant information
    restaurantName: 'LA Baker',
    restaurantUrl: 'https://www.labaker.com/'
};

