// Configuration template file
// For local development: Copy this file to config.js and add your actual API key
// For production: The config.js is auto-generated by GitHub Actions using secrets

const CONFIG = {
    n8nWebhookUrl: 'https://n8n.srv1155798.hstgr.cloud/webhook/8f0737aa-cde7-4089-bd96-7690120f89f7/chat',
    
    // OpenAI API Key - Get from: https://platform.openai.com/api-keys
    // This key is ONLY used for generating 2 sample follow-up questions
    // For production: Set OPENAI_API_KEY in GitHub Secrets
    // For local: Add your key here in config.js (gitignored)
    openaiApiKey: 'sk-your-openai-api-key-here',
    
    // OpenAI Proxy URL (optional) - Use a serverless function to avoid CORS issues
    // Example: 'https://your-vercel-app.vercel.app/api/openai-proxy'
    // Leave empty to try direct API call (may fail due to CORS on GitHub Pages)
    openaiProxyUrl: '',
    
    restaurantName: 'LA Baker',
    restaurantUrl: 'https://www.labaker.com/'
};

